// Demo calibration records — pre-seeded for hackathon demo.
// Shows the Calibration Summary with realistic data on first load.

import type { CalibrationRecord } from "@/lib/calibration/types";

const PROJECT_ID = "p-mesa-stormdrain-2026";
const ts = (daysAgo: number) =>
  new Date(Date.now() - daysAgo * 86400000).toISOString();

export const DEMO_CALIBRATION_RECORDS: CalibrationRecord[] = [
  // ── Evidence approvals ──────────────────────────
  {
    id: "cal-ev-demo-1",
    timestamp: ts(5),
    projectId: PROJECT_ID,
    evidenceId: "ev-schedule-update",
    riskItemId: "A-E1",
    action: "approved",
    objectType: "evidence",
    predicted: { noticeRisk: false, costDelta: 0, scheduleDelta: 15, clauseRefs: [], confidence: 95 },
    final: { noticeRisk: false, costDelta: 0, scheduleDelta: 15, clauseRefs: [], confidence: 95 },
    diff: [],
    reasonCodes: [],
    sourceProvenance: ["upload:Schedule Update — Phase 2 Rev 3.xlsx"],
    confidenceAtTime: 95,
    userRole: "pm",
  },
  {
    id: "cal-ev-demo-2",
    timestamp: ts(4),
    projectId: PROJECT_ID,
    evidenceId: "ev-budget-review",
    riskItemId: "A-E1",
    action: "approved",
    objectType: "evidence",
    predicted: { noticeRisk: false, costDelta: 12000, scheduleDelta: 0, clauseRefs: ["§7.3.1"], confidence: 72 },
    final: { noticeRisk: false, costDelta: 12000, scheduleDelta: 0, clauseRefs: ["§7.3.1"], confidence: 72 },
    diff: [],
    reasonCodes: ["missing_citation"],
    sourceProvenance: ["gmail:FW: Q1 Budget Review — Director Chen"],
    confidenceAtTime: 72,
    userRole: "pm",
  },
  {
    id: "cal-ev-demo-3",
    timestamp: ts(3),
    projectId: PROJECT_ID,
    evidenceId: "ev-procore-rfi",
    action: "rejected",
    objectType: "evidence",
    predicted: { noticeRisk: true, costDelta: 5000, scheduleDelta: 3, clauseRefs: ["§12.4"], confidence: 58 },
    final: {},
    diff: [{ field: "status", before: "pending", after: "rejected" }],
    reasonCodes: ["irrelevant", "missing_citation"],
    sourceProvenance: ["procore:RFI-047 Response Draft"],
    confidenceAtTime: 58,
    userRole: "pm",
  },

  // ── Suggestion accepts ──────────────────────────
  {
    id: "cal-sg-demo-1",
    timestamp: ts(4),
    projectId: PROJECT_ID,
    suggestionId: "sug-notice-A-E1",
    riskItemId: "A-E1",
    action: "approved",
    objectType: "suggestion",
    predicted: { headline: "Notice clock active — §7.3.1", confidence: 92, impact: "high", costAmount: undefined, scheduleDays: undefined },
    final: { headline: "Notice clock active — §7.3.1", confidence: 92, impact: "high" },
    diff: [],
    reasonCodes: [],
    sourceProvenance: ["log-2026-02-12"],
    confidenceAtTime: 92,
    userRole: "pm",
    resolverRule: "notice_risk",
  },
  {
    id: "cal-sg-demo-2",
    timestamp: ts(3),
    projectId: PROJECT_ID,
    suggestionId: "sug-alignment-A-E3",
    riskItemId: "A-E3",
    action: "approved",
    objectType: "suggestion",
    predicted: { headline: "Field/office misalignment detected", confidence: 78, impact: "medium" },
    final: { headline: "Field/office misalignment detected", confidence: 78, impact: "medium" },
    diff: [],
    reasonCodes: [],
    sourceProvenance: ["log-2026-02-13"],
    confidenceAtTime: 78,
    userRole: "pm",
    resolverRule: "alignment_change",
  },

  // ── Suggestion edits (corrections) ──────────────
  {
    id: "cal-sg-demo-3",
    timestamp: ts(2),
    projectId: PROJECT_ID,
    suggestionId: "sug-cost-A-E1",
    riskItemId: "A-E1",
    action: "edited",
    objectType: "suggestion",
    predicted: { headline: "Cost estimate understated", confidence: 85, impact: "high", costAmount: 38000 },
    final: { headline: "Cost estimate understated", confidence: 85, impact: "high", costAmount: 45000 },
    diff: [{ field: "costAmount", before: 38000, after: 45000 }],
    reasonCodes: ["wrong_cost_range"],
    sourceProvenance: ["log-2026-02-12", "doc-A-D2"],
    confidenceAtTime: 85,
    userRole: "pm",
    resolverRule: "cost_revision",
  },
  {
    id: "cal-sg-demo-4",
    timestamp: ts(2),
    projectId: PROJECT_ID,
    suggestionId: "sug-schedule-A-E2",
    riskItemId: "A-E2",
    action: "edited",
    objectType: "suggestion",
    predicted: { headline: "Schedule impact understated", confidence: 74, impact: "medium", scheduleDays: 4 },
    final: { headline: "Schedule impact understated", confidence: 74, impact: "medium", scheduleDays: 6 },
    diff: [{ field: "scheduleDays", before: 4, after: 6 }],
    reasonCodes: ["wrong_schedule_impact"],
    sourceProvenance: ["log-2026-02-11"],
    confidenceAtTime: 74,
    userRole: "pm",
    resolverRule: "schedule_revision",
  },

  // ── Notice confirmation ─────────────────────────
  {
    id: "cal-nt-demo-1",
    timestamp: ts(4),
    projectId: PROJECT_ID,
    suggestionId: "sug-notice-A-E1",
    riskItemId: "A-E1",
    action: "approved",
    objectType: "notice",
    predicted: { clauseRef: "§7.3.1", deadline: "2026-02-14T23:59:00-08:00" },
    final: { clauseRef: "§7.3.1", deadline: "2026-02-14T23:59:00-08:00", recipientGroup: "pm", method: "email" },
    diff: [],
    reasonCodes: [],
    sourceProvenance: ["log-2026-02-12"],
    confidenceAtTime: 92,
    userRole: "pm",
    resolverRule: "notice_risk",
  },

  // ── Suggestion rejection ────────────────────────
  {
    id: "cal-sg-demo-5",
    timestamp: ts(1),
    projectId: PROJECT_ID,
    suggestionId: "sug-contract-A-E2",
    riskItemId: "A-E2",
    action: "rejected",
    objectType: "suggestion",
    predicted: { headline: "Missing clause reference §301.2", confidence: 65, impact: "low" },
    final: {},
    diff: [],
    reasonCodes: ["irrelevant"],
    sourceProvenance: ["doc-A-D3"],
    confidenceAtTime: 65,
    userRole: "pm",
    resolverRule: "contract_reference",
  },

  // ── Another cost edit (shows pattern) ───────────
  {
    id: "cal-sg-demo-6",
    timestamp: ts(1),
    projectId: PROJECT_ID,
    suggestionId: "sug-cost-A-E1-v2",
    riskItemId: "A-E1",
    action: "edited",
    objectType: "suggestion",
    predicted: { headline: "Revised cost exposure", confidence: 80, impact: "high", costAmount: 42000 },
    final: { headline: "Revised cost exposure", confidence: 80, impact: "high", costAmount: 48000 },
    diff: [{ field: "costAmount", before: 42000, after: 48000 }],
    reasonCodes: ["wrong_cost_range"],
    sourceProvenance: ["log-2026-02-14"],
    confidenceAtTime: 80,
    userRole: "pm",
    resolverRule: "cost_revision",
  },
];
